import { Post } from './types'

export const dummyPosts: Post[] = [
  {
    _id: '1',
    id: '1',
    title: 'Water Supply Issue in Downtown Aleppo',
    content: 'Residents reporting low water pressure in the downtown area. Investigation needed to identify the source of the problem.',
    authorId: 'client-1',
    authorName: 'Ahmed Al-Mansouri',
    status: 'pending',
    category: 'water',
    priority: 'high',
    tags: ['water', 'infrastructure', 'urgent'],
    location: {
      latitude: 36.2021,
      longitude: 37.1343,
      address: 'Al-Jamiliyah District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '2',
    id: '2',
    title: 'Electricity Outage in Residential Area',
    content: 'Power outage reported in the northern residential district. Multiple buildings affected. Emergency response required.',
    authorId: 'client-2',
    authorName: 'Fatima Al-Zahra',
    status: 'approved',
    category: 'electricity',
    priority: 'critical',
    tags: ['electricity', 'outage', 'emergency'],
    location: {
      latitude: 36.2150,
      longitude: 37.1450,
      address: 'Al-Aziziyah District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '3',
    id: '3',
    title: 'Road Maintenance Required',
    content: 'Potholes and cracks detected on main highway. Needs immediate attention to ensure road safety.',
    authorId: 'client-3',
    authorName: 'Mohammed Al-Saud',
    status: 'published',
    category: 'road',
    priority: 'medium',
    tags: ['road', 'maintenance', 'safety'],
    location: {
      latitude: 36.1900,
      longitude: 37.1200,
      address: 'Al-Sabil District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '4',
    id: '4',
    title: 'Street Lighting Issue',
    content: 'Several street lights are not working in the commercial district. Affecting pedestrian safety at night.',
    authorId: 'client-4',
    authorName: 'Sara Al-Rashid',
    status: 'pending',
    category: 'street_light',
    priority: 'medium',
    tags: ['lighting', 'safety', 'commercial'],
    location: {
      latitude: 36.2050,
      longitude: 37.1400,
      address: 'Al-Midan District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '5',
    id: '5',
    title: 'Building Structural Damage',
    content: 'Structural damage reported in residential building. Requires immediate professional inspection.',
    authorId: 'client-5',
    authorName: 'Khalid Al-Mutairi',
    status: 'approved',
    category: 'building',
    priority: 'high',
    tags: ['building', 'structural', 'urgent'],
    location: {
      latitude: 36.2100,
      longitude: 37.1300,
      address: 'Al-Shaar District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '6',
    id: '6',
    title: 'Wall Collapse Risk',
    content: 'Damaged wall showing signs of potential collapse. Immediate safety measures required.',
    authorId: 'client-6',
    authorName: 'Noura Al-Harbi',
    status: 'published',
    category: 'wall',
    priority: 'critical',
    tags: ['wall', 'safety', 'collapse'],
    location: {
      latitude: 36.2000,
      longitude: 37.1350,
      address: 'Al-Fardous District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '7',
    id: '7',
    title: 'Suspected Landmine Area',
    content: 'Potential landmine area identified. Requires immediate professional clearance and safety measures.',
    authorId: 'client-7',
    authorName: 'Omar Al-Ghamdi',
    status: 'pending',
    category: 'mine',
    priority: 'critical',
    tags: ['mine', 'safety', 'clearance'],
    location: {
      latitude: 36.1950,
      longitude: 37.1250,
      address: 'Al-Hamidiyah District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '8',
    id: '8',
    title: 'Water Pipeline Leak',
    content: 'Water leaking from underground pipeline. Water pooling on the street surface. Needs immediate repair.',
    authorId: 'client-8',
    authorName: 'Layla Al-Shammari',
    status: 'approved',
    category: 'water',
    priority: 'high',
    tags: ['water', 'leakage', 'repair'],
    location: {
      latitude: 36.2080,
      longitude: 37.1380,
      address: 'Al-Kallasa District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '9',
    id: '9',
    title: 'Electrical Grid Failure',
    content: 'Major electrical grid failure affecting multiple neighborhoods. Emergency response team dispatched.',
    authorId: 'client-9',
    authorName: 'Yousef Al-Qahtani',
    status: 'published',
    category: 'electricity',
    priority: 'critical',
    tags: ['electricity', 'grid', 'emergency'],
    location: {
      latitude: 36.2120,
      longitude: 37.1420,
      address: 'Al-Salihin District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '10',
    id: '10',
    title: 'Road Damage from Conflict',
    content: 'Severe road damage from previous conflict. Multiple craters and debris blocking traffic.',
    authorId: 'client-10',
    authorName: 'Maha Al-Otaibi',
    status: 'rejected',
    category: 'road',
    priority: 'high',
    tags: ['road', 'damage', 'conflict'],
    location: {
      latitude: 36.1850,
      longitude: 37.1150,
      address: 'Al-Bab District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '11',
    id: '11',
    title: 'Street Light Pole Damaged',
    content: 'Street light pole severely damaged and leaning. Risk of falling. Requires immediate replacement.',
    authorId: 'client-11',
    authorName: 'Ali Al-Hassan',
    status: 'pending',
    category: 'street_light',
    priority: 'high',
    tags: ['street_light', 'damage', 'safety'],
    location: {
      latitude: 36.1980,
      longitude: 37.1320,
      address: 'Al-Jdeideh District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '12',
    id: '12',
    title: 'Building Facade Damage',
    content: 'Building facade showing significant damage. Loose materials pose risk to pedestrians below.',
    authorId: 'client-12',
    authorName: 'Rania Al-Mahmoud',
    status: 'approved',
    category: 'building',
    priority: 'medium',
    tags: ['building', 'facade', 'safety'],
    location: {
      latitude: 36.2030,
      longitude: 37.1370,
      address: 'Al-Tawhid District, Aleppo, Syria',
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'admin-1',
    reviewedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
